name: a1_sim
robot_params:
  body_mass: 10
  body_inertia: [ 0.24, 0, 0, 0, 0.80, 0, 0, 0, 1.0 ]
  body_height: 0.28
  hip_l: 0.08505
  upper_l: 0.2
  lower_l: 0.2

  velocity:  
    #com_offset: [ 0.005, 0.00145, 0.000515 ] # vel mode
    com_offset: [ 0.0, 0.0, 0.0 ] # vel mode
  position:
    com_offset: [ -0.005, 0.0024, 0.000515 ] # pos mode
  walk:
    com_offset: [ -0.005, 0.0012, 0.000515 ] # walk mode
    # com_offset: [ -0.01, 0.003, 0.000515 ] # mpc/walk
  hip_offset: [ [ 0.1805, -0.047, 0. ],
                [ 0.1805, 0.047, 0. ],
                [ -0.1805, -0.047, 0. ],
                [ -0.1805, 0.047, 0. ] ]
  default_hip_positions: [ [ 0.17, -0.135, 0 ],
                           [ 0.17, 0.135, 0 ],
                           [ -0.195, -0.135, 0 ],
                           [ -0.195, 0.135, 0 ] ]
  default_standup_angle:
    ab: 0
    hip: 0.9
    knee: -1.8

  default_sitdown_angle:
    ab: -0.167136
    hip: 0.934969
    knee: -2.54468

motor_params:
  kps: [ 100,100,100 ]
  kds: [ 1.0,1.0,1.0 ]
  joint_directions: [ 1,1,1, 1,1,1, 1,1,1, 1,1,1 ]
  joint_offsets: [ 0,0,0, 0,0,0, 0,0,0, 0,0,0 ]
  stand_angle: [ 0,0.67,-1.25 ]

  abad_p: 100.0
  abad_d: 1.0
  hip_p: 100.0
  hip_d: 2.0
  knee_p: 100.0
  knee_d: 2.0

# is simulate or not
is_sim: true
